image: ubuntu:18.04

before_script:
  - apt-get update
  - apt-get install python3.6
  - python3 -m pip install -r requirements.txt

spec:
  script:
    - apt-get install ffmpeg
    - python3 -m pip install nose2
    - nose2 -v --with-coverage
  
pylint:
  script:
    - python3 -m pip install pylint
    - pylint --errors-only *.py
